name: Build and Deploy Static Site

on:
  push:
    branches:
      - main  
    paths:
    - '**.md'  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm init -y
          npm install markdown-it highlight.js markdown-it-katex

      - name: Create output directory
        run: mkdir -p output

      - name: Convert Markdown to HTML
        run: |
          for file in src/*.md; do
            if [ "$(basename "$file")" != "README.md" ]; then
              node -e "
                const fs = require('fs');
                const MarkdownIt = require('markdown-it');
                const katex = require('markdown-it-katex');
                const hljs = require('highlight.js');
                
                const md = new MarkdownIt({
                  highlight: function (str, lang) {
                    if (lang && hljs.getLanguage(lang)) {
                      try {
                        return hljs.highlight(str, { language: lang }).value;
                      } catch (__) {}
                    }
                    return ''; // use external default escaping
                  }
                }).use(katex);
                
                const input = fs.readFileSync('$file', 'utf8');
                const output = md.render(input);
                fs.writeFileSync('output/$(basename "$file" .md).html', output);
              "
            fi
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output