name: Markdown to PDF Conversion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Output Directory
        run: mkdir -p output

      - name: Convert Markdown to PDF
        run: |
          for file in $(find notes/ -name '*.md'); do
            filename=$(basename "$file" .md)
            output_file="output/$filename.pdf"
            echo "Converting $file to $output_file"
            npx @marp-team/marp-cli "$file" -o "$output_file"
          done

      - name: List Output Directory
        run: ls -R output

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add output/
          git diff-index --quiet HEAD || git commit -m "Convert Markdown to PDF and move to output directory"
          git push