name: markdown 2 html

on:
  push:
    paths:
      - '**.md'
      - '!README.md' # exclude the README.md file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install pandoc and MathJax
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          npm install mathjax-node-cli -g

      - name: Convert Markdown to HTML
        run: |
          mkdir -p output
          for file in *.md; do
            if [ "$file" != "README.md" ]; then
              pandoc --mathjax -s "$file" -o "output/${file%.md}.html"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "Compile Markdown to HTML"
          git push
